
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

import subprocess
from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\owner\Desktop\לימודים - שנה ג\סמסטר א\Tkinter-Designer-master (1)\Tkinter-Designer-master\build\assets\frame0")


ASSETS_PATH1=OUTPUT_PATH/Path(r"Images_UI/frame_2")
def relative_to_assets1(path: str) -> Path:
    return ASSETS_PATH1 / Path(path)


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("440x650")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 650,
    width = 440,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)
def click_b1():
    window.destroy()
    subprocess.call(['python', 'page1_tk.py'])

canvas.place(x = 0, y = 0)
button_image_1 = PhotoImage(
    file=relative_to_assets1("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: click_b1(),
    relief="flat"
)
button_1.place(
    x=14.0,
    y=31.0,
    width=27.0,
    height=27.06114959716797
)

image_image_1 = PhotoImage(
    file=relative_to_assets1("image_1.png"))
image_1 = canvas.create_image(
    220.0,
    110.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets1("image_2.png"))
image_2 = canvas.create_image(
    115.0,
    277.0,
    image=image_image_2
)
def click_b2():
    window.destroy()
    subprocess.call(['python', 'page3_tk.py'])

button_image_2 = PhotoImage(
    file=relative_to_assets1("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: click_b2(),
    relief="flat"
)
button_2.place(
    x=239.0,
    y=302.0,
    width=146.0,
    height=40.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets1("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=39.0,
    y=302.0,
    width=146.0,
    height=40.0
)

image_image_3 = PhotoImage(
    file=relative_to_assets1("image_3.png"))
image_3 = canvas.create_image(
    311.0,
    277.0,
    image=image_image_3
)
def click_b4():
    window.destroy()
    subprocess.call(['python', 'page4_tk.py'])


button_image_4 = PhotoImage(
    file=relative_to_assets1("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: click_b4(),
    relief="flat"
)
button_4.place(
    x=160.0,
    y=456.0,
    width=120.0,
    height=55.0
)

image_image_4 = PhotoImage(
    file=relative_to_assets1("image_4.png"))
image_4 = canvas.create_image(
    220.0,
    430.0,
    image=image_image_4
)
window.resizable(False, False)
window.mainloop()
